config/routes.rb
Rails.application.routes.draw do

  # crée 7 routes différentes pour chaque ressource: index, show, new, edit, create, updateet et destroy
  resources :friends
  resources :annotations

  # SET DEFAULT ROUTE: put it at the top of the file, should be matched first.
  root 'welcome#index'
  get 'welcome/index'


  # get '/friends/:id', to: 'friends#show'
  get '/friends/destroy/:id', to: 'friends#destroy'
  get '/annotations/destroy/:id', to: 'annotations#destroy'
  #get '/friends/:id' => 'friends#show', as: 'post'
end

app/models/annotation.rb
class Annotation < ApplicationRecord

  # tables relations
  belongs_to :friend
  # validations
  validates :body,      presence: true
  validates :friend_id, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  
  # ================  tables relations =======================
  has_many :annotations

  # ================  validations =======================
  validates :name,    presence: true, format: { with: /[[:alpha:]]/, message: 'only alphabetic character' }
  validates :phone,   presence: true, format: { with: /[[:digit:]]/, message: 'only number please' }
  validates :address, presence: true
  validates :email,   presence: true, uniqueness: true
  validates :sex,     presence: true

  # Custome validations
  # def sex_description_validation
  #   if self.sex.blank?
  #     " - "
  #   else
  #     self.sex
  #   end
  # end

  # Cherche un registre par attribut
  def self.findBy(query)
    where("name like ?", "%#{query}%")
  end

end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController

  # ========================= Configuration =====================
  before_action :set_annotation, only: %i[show edit update destroy]
  before_action :set_friend, only: %i[create new edit update]

  # GET /annotations or /annotations.json
  def index
    @annotations = Annotation.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /annotations/1 or /annotations/1.json
  def show
    # has  @annotation = Annotation.find(params[:id])
  end

  # GET /annotations/new
  def new
    @annotation = Annotation.new
    # Has @friends = Friend.all
  end

  # GET /annotations/1/edit
  def edit
    # has  @annotation = Annotation.find(params[:id])
    # Has @friends = Friend.all
  end

  # POST /annotations or /annotations.json
  def create
    @annotation = Annotation.new(annotation_params)

    respond_to do |format|
      if @annotation.save
        format.html { redirect_to annotation_url(@annotation), notice: "Annotation was successfully created." }
        format.json { render :show, status: :created, location: @annotation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annotations/1 or /annotations/1.json
  def update
    respond_to do |format|
      if @annotation.update(annotation_params)
        format.html { redirect_to annotation_url(@annotation), notice: "Annotation was successfully updated." }
        format.json { render :show, status: :ok, location: @annotation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annotations/1 or /annotations/1.json
  def destroy
    # has  @annotation = Annotation.find(params[:id])
    @annotation.destroy

    respond_to do |format|
      format.html { redirect_to annotations_url, notice: "Annotation was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  # ========================= Méthodes de configuration =====================
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

  def set_friend
    @friends = Friend.all
  end
    # Only allow a list of trusted parameters through.
    def annotation_params
      params.require(:annotation).permit(:body, :friend_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  # ========================= Configuration =====================
  before_action :set_friend, only: %i[show edit update destroy]

  # GET /friends or /friends.json
  def index
    # if has search, show one
    if params[:to_search]
      @friends = Friend.findBy(params[:to_search]).paginate(page: params[:page], per_page: 10)
    else
      # show all
      @friends = Friend.all.paginate(page: params[:page], per_page: 10)
    end
  end

  # GET /friends/1 or /friends/1.json
  def show
    # @friend = Friend.find(params[:id])
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
    #  @friend = Friend.find(params[:id])
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    # Check is'il y a une association
    a = Annotation.find_by(friend_id: @friend.id)
    if(a != nil)
      a.destroy
    end

    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # ========================= Méthodes de configuration =====================
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :address, :email, :phone, :sex, :id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
# Os helps colocados aqui seram visiveis em toda a aplicacao
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/annotations/_form.html.erb
<%= form_with(model: annotation) do |form| %>

  <% if annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>
      <ul>
        <% annotation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </div>

  <div class="field">
    <div class="field">
      <%= form.label :friend_id %>
      <%= form.collection_select(:friend_id, @friends, :id, :name, include_blank: "Choix..." )  %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/annotations/edit.html.erb
<h1>Editing Annotation</h1>

<%= render 'form', annotation: @annotation %>

<%= link_to 'Show', @annotation %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Annotations</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Body</th>
      <th>Friend</th>
      <th colspan="3">ACTIONS</th>
    </tr>
  </thead>
  <tbody>
    <% @annotations.each do |annotation| %>
      <tr>
        <td><i><%= annotation.body %></i></td>
        <td><%= annotation.friend.name %></td>
        <td><strong><%= link_to 'Show', annotation %></strong></td>
        <td><strong><%= link_to 'Edit', edit_annotation_path(annotation) %></strong></td>
        <td><strong><%#= link_to 'Destroy', annotation, method: :delete, data: { confirm: 'Are you sure?' } %></strong></td>
        <td><a href="/annotations/destroy/<%= annotation.id %>">Destroy</a> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- render page links in the view: -->
<%= will_paginate @annotations %>
<br>
<%= link_to 'New Annotation', new_annotation_path %>

app/views/annotations/new.html.erb
<h1>New Annotation</h1>

<%= render 'form', annotation: @annotation %>
<br>
<%= link_to 'Back', annotations_path %>

app/views/annotations/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Show page</h1>
<p><strong>Body:</strong><%= @annotation.body %></p>
<p><strong>Belongs to Friend:</strong><%= @annotation.friend.name %></p>
<br>
<%= link_to 'Edit', edit_annotation_path(@annotation) %> |
<%= link_to 'Back', annotations_path %>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>

  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.select( :sex,options_for_select([["Male", "M"], ["Femalle", "F"]],@friend.sex ), { include_blank: "Choix..." } ) %>
    <%#= form.select( :sex,options_for_select([["Male", "M"], ["Femalle", "F"]],@friend.sex ), { include_blank: @friend.sex_description_validation } ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(friends_path, :method => :get) do %>
  <%= text_field_tag 'to_search', nil, placeholder: 'Enter search term...' %>
  <%= submit_tag "Find" %>
<% end %>

<h1>Friends</h1>

<table class="table table-striped">
<thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.address %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.sex %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%#= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><a href="/friends/destroy/<%= friend.id %>">Destroy</a> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- render page links in the view: -->
<%= will_paginate @friends %>
<br>

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Show page</h1>
<p><strong>Name:    </strong><%= @friend.name %></p>
<p><strong>Address: </strong><%= @friend.address %></p>
<p><strong>Email:   </strong><%= @friend.email %></p>
<p><strong>Phone:   </strong><%= @friend.phone %></p>
<p><strong>Sex:     </strong><%= @friend.sex %></p>

<% if(@friend.annotations.length > 0) %>
  <hr>
  <br>
  <h3>Lista das anotacoes associadas(<%= @friend.annotations.length %>)</h3>
  <% @friend.annotations.each do |annotation| %>
    <li>Content: <%= annotation.body %> </li>
    <br>
  <% end %>
  <br>
<% end %>
<br>
<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Remember" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  </head>
  <body>
  <!--=========================== MENU ========================-->
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path  %>">Remember</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <!--==== render page view =====-->
        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <br>
        <!--======== Sidebar =========-->
        <div class="col-lg-2">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Inicio", root_path  %></li>
              <li><%= link_to "Anotação", annotations_path  %></li>
              <li><%= link_to "Amigos", friends_path  %></li>
            </ul>
          </div>
        </div>
      </div>
      <!--=========================== FOOTER ========================-->
      <br>
      <footer>
        <p>&copy; Company 2022</p>
      </footer>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>


</div>